name: Deploy to AWS Lambda
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Package Lambda
        run: |
          pip install -r requirements.txt -t ./package
          cp -r src ./package/
          cp lambda_handler.py ./package/
          cd package && zip -r ../deployment.zip . -x "*.pyc" -x "__pycache__/*"
      
      - name: Deploy Lambda
        run: |
          aws s3 mb s3://aiawsattack-bucket || true
          aws s3 cp deployment.zip s3://aiawsattack-bucket/marketing-crew/deployment.zip
          aws lambda update-function-code \
            --function-name content-strategy-crew \
            --s3-bucket aiawsattack-bucket \
            --s3-key marketing-crew/deployment.zip \
            --publish
          
          echo "Deployed! Invoke with:"
          echo "aws lambda invoke --function-name content-strategy-crew output.json"