name: Deploy to AWS Lambda
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and Deploy
        run: |
          # Get account ID
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          # Create ECR repository if it doesn't exist
          aws ecr create-repository --repository-name marketing-crew || true
          
          # Build and push Docker image
          docker build -t marketing-crew .
          docker tag marketing-crew:latest $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/marketing-crew:latest
          docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/marketing-crew:latest
          
          # Create S3 bucket if it doesn't exist (for future use)
          aws s3 mb s3://aiawsattack-bucket || true
          
          # Create IAM role if it doesn't exist
          aws iam create-role \
            --role-name lambda-execution-role \
            --assume-role-policy-document '{
              "Version": "2012-10-17",
              "Statement": [{
                "Effect": "Allow",
                "Principal": {"Service": "lambda.amazonaws.com"},
                "Action": "sts:AssumeRole"
              }]
            }' || true
          
          aws iam attach-role-policy \
            --role-name lambda-execution-role \
            --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole || true
          
          aws iam attach-role-policy \
            --role-name lambda-execution-role \
            --policy-arn arn:aws:iam::aws:policy/AmazonBedrockFullAccess || true
          
          # Wait for role to propagate
          sleep 10
          
          # Create or update Lambda function
          aws lambda create-function \
            --function-name content-strategy-crew \
            --package-type Image \
            --code ImageUri=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/marketing-crew:latest \
            --role arn:aws:iam::$ACCOUNT_ID:role/lambda-execution-role \
            --timeout 900 \
            --memory-size 3008 \
            --environment Variables={HOME=/tmp} \
            || aws lambda update-function-code \
                --function-name content-strategy-crew \
                --image-uri $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/marketing-crew:latest
          
          echo "Deployed! Invoke with:"
          echo "aws lambda invoke --function-name content-strategy-crew output.json"